# Generated by Django 4.0.4 on 2022-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basins', '0003_basin_conf_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasinId',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
