# Generated by Django 4.0.4 on 2022-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basins', '0004_basinid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basinid',
            options={'verbose_name': 'mavjud qurilma', 'verbose_name_plural': 'mavjud qurilmalar'},
        ),
        migrations.AlterField(
            model_name='basinid',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name="Qurilma 'id' si"),
        ),
        migrations.AlterField(
            model_name='basinmessage',
            name='bat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='batareya quvvati (volt)'),
        ),
    ]
