# Generated by Django 4.0.4 on 2022-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Telegram id'),
        ),
    ]
